backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Homepage"
    files:
      - file: "data/home.json"
        label: "Hero Section"
        fields:
          - { label: "Hero Title Line 1", name: "line1", widget: "string" }
          - { label: "Hero Title Line 2", name: "line2", widget: "string" }
          - { label: "Hero Accent", name: "accent", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }